set(CMAKE_SYSTEM_NAME             Generic)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(TOOLCHAIN          riscv32-unknown-elf)
set(AR                 ${TOOLCHAIN}-ar)
set(AS                 ${TOOLCHAIN}-as)
set(CC                 ${TOOLCHAIN}-gcc)
set(CPP                ${TOOLCHAIN}-g++)
set(LD                 ${TOOLCHAIN}-ld)
set(GDB                ${TOOLCHAIN}-gdb)
set(OBJCOPY            ${TOOLCHAIN}-objcopy)
set(OBJDUMP            ${TOOLCHAIN}-objdump)
set(SIZE               ${TOOLCHAIN}-size)
set(READELF            ${TOOLCHAIN}-readelf)
