name: RED-V_SiFive_RISC-V_FE310_SoC
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  target-gcc-riscv64-unknown-elf:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: update-tools
        run: |
          sudo apt install gcc-riscv64-unknown-elf
      - name: target-riscv64-unknown-elf
        run: |
          bash ./Rebuild.sh
          ls -la ./Output/Blinky_RedV_FE310.hex
  target-gcc-riscv64-unknown-elf-cmake:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: update-tools
        run: |
          sudo apt install gcc-riscv64-unknown-elf
      - name: target-riscv64-unknown-elf
        run: |
          mkdir -p Output && cd Output
          cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain-unix.cmake .. && make
          ls -la ./Blinky_RedV_FE310.hex
